# Generated by Django 5.1.3 on 2025-11-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UsersTemplates",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("session_id", models.CharField(blank=True, max_length=255, null=True)),
                ("token", models.CharField(max_length=255, unique=True)),
                ("template_code", models.CharField(max_length=15, unique=True)),
                ("template_id", models.CharField(max_length=5)),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
