# Generated by Django 5.1.3 on 2025-11-07 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminPanelWhitelist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ipv4_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="The IPv4 address for which the admin panel access is being controlled.",
                        null=True,
                        protocol="IPv4",
                    ),
                ),
                (
                    "also_check_ipv4_address",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether to also check the IPv4 address when validating admin panel access.",
                    ),
                ),
                (
                    "activation_url",
                    models.CharField(
                        blank=True,
                        help_text="The unique activation URL generated for the user session to access the admin panel. This URL is valid for a limited time.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "activation_token",
                    models.CharField(
                        blank=True,
                        help_text="The unique activation token associated with the activation URL. This token is used to verify the authenticity of the activation request.",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        choices=[(True, "Allowed"), (False, "Blocked")],
                        default=False,
                        help_text="Indicates whether the user session is allowed or blocked from accessing the admin panel.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the user is currently activated to see the admin panel Browser sessions.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the whitelist entry was created.",
                    ),
                ),
                (
                    "active_on",
                    models.DateTimeField(
                        blank=True,
                        help_text="The timestamp when the user session was activated for admin panel access.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user associated with this whitelist entry.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
