# Generated by Django 5.1.3 on 2025-11-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WishCraft_admin_panel_protection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminpanelwhitelist",
            name="user_agent",
            field=models.CharField(
                blank=True,
                help_text="The user agent string of the browser/client used to access the admin panel.",
                max_length=1024,
                null=True,
            ),
        ),
    ]
